services:
  - type: web
    name: constructora-cchang-api
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOW_SYNC
        value: "false"
      - key: DB_LOGGING
        value: "false"